TDL-16054 added code comments
singer-io/tap-google-sheets pull request #52
Opened 2021-10-29 05:48 UTC by namrata270998

# Description of change
added code comments

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-12-02 10:42 UTC, savan-chovatiya commented on tap_google_sheets/schema.py
> +            # if the column is to be skiped or not for each column in the list
```suggestion
            # if the column is to be skipped or not for each column in the list
```

2021-12-02 11:41 UTC, namrata270998 commented on tap_google_sheets/schema.py
> +            # if the column is to be skiped or not for each column in the list
done

2021-12-02 11:48 UTC, savan-chovatiya approved these changes

2021-12-08 09:05 UTC, karanpanchal-crest approved these changes

2021-12-08 18:04 UTC, KrisPersonal requested changes
Is commenting only applicable for schema.py? Are there no other comments required for other code?

2021-12-09 04:26 UTC, namrata270998 commented
> Is commenting only applicable for schema.py? Are there no other comments required for other code?
The other files including this file also had covered code comments in the majority of the code. The schema.py file contained most of the logic of the tap. Hence, tried to incorporate more code comments for better readability and understanding.

2021-12-09 18:14 UTC, KrisPersonal approved these changes

2021-12-13 06:14 UTC, merged